- .pre-commit-config.yaml
- docs/source/upcoming_release_notes/4-bld_precommit_autoupdate.rst
- superscore/tests/test_compare.py
Run `pre-commit autoupdate`
we recently updated our runners, which moved the default python version to 3.12.  For the test runners this doesn't matter since we make an env with a specific python version, but this broke some of the older the pre-commit check hooks (flake8)
I've been told this is more ammo for switching to ruff, but I'm lazy.
CI should pass
This PR
> BLD: update pre-commit config

- superscore/backends/__init__.py
- superscore/backends/directory.py
- superscore/backends/filestore.py
- superscore/bin/demo_main.py
- superscore/bin/ui_main.py
- superscore/model.py
- superscore/tests/conftest.py
- superscore/tests/demo.cfg
- superscore/tests/test_backend.py
* Implement `DirectoryBackend`, which disperses entries into multiple files within a directory
* Change demo config to use `DirectoryBackend`
* Adjust Tag type so serialization continues to work
* Introduce `_Backend.reset` to aid in testing and demos
`FilestoreBackend` has very poor performance scaling, since the same large file has to read and written whenever data changes in the backend.  It also has extra complexity from `_entry_cache`, which is a common source of bugs due to improper cache invalidation and write-through handling.  `DirectoryBackend` is a solution to both of these problems, while also satisfying the need for a convenient testing / debugging backend.
`DirectoryBackend` has been inserted into existing backend tests, ensuring it has the same capabilities as existing …
> ENH: add DirectoryBackend

- superscore/widgets/snapshot_table.py
- superscore/widgets/window.py
* Implement `SnapshotTableModel`
* Instantiate `QTableView` connected to `SnapshotTableModel` in `Window.setup_ui()`
Relates to [SWAPPS-197](https://jira.slac.stanford.edu/browse/SWAPPS-197)
This table lets users browse Snapshots in chronological order.
No tests have been added or had to be modified.  Works interactively.
> GUI: add snapshot table, without support for meta PV columns

- superscore/widgets/pv_details_components.py
Adds two PV Details popups, a readonly and an editable:
Readonly (left: mockup, right: implemented):
Editable:
Placeholders are left for the tag chips implementation.
A PVDetails dataclass is implemented for supplying these popups with data.
The editable popup can be supplied with initial data (to edit an existing PV, for example):
Doing so changes the title and button text appropriately
Closes [SWAPPS-201](https://jira.slac.stanford.edu/browse/SWAPPS-201)
Closes [SWAPPS-202](https://jira.slac.stanford.edu/browse/SWAPPS-202)
These popups are to be used to present PV information or create new PV entries.
Interactively. The __main__ has a little demo that can be run with:
`python pv_details_components` (we can remove this before merging in).
Additional validation of inputs can be added on, …
> GUI: Add read-only and editable popups for PV details

- superscore/tests/test_page.py
* explicitly set date before searching in `test_page::test_apply_filter`
The test relied on the test data having dates within the search page's range, but the search page set it's range to be the previous year.  The test data have a date of `10 May 2024`, so the test began failing on `10 May 2025`.  By explicitly setting the date range in the test, this type of sudden failure should not occur.
Run the test suite.
> TST: explicitly set date before searching in test_page::test_apply_filter

- superscore/backends/core.py
- superscore/backends/directory.py
- superscore/backends/filestore.py
- superscore/backends/test.py
- superscore/client.py
- superscore/model.py
- superscore/tests/conftest_data.py
- superscore/type_hints.py
- superscore/widgets/snapshot_table.py
* move meta PVs definition out of `Collection` class def
* add meta PV getter and setter to backends
* add meta PV test data to `linac_data` fixture
* adjust `AnyEpicsType` type hint to improve coercion behaviour
Closes [SWAPPS-214](https://jira.slac.stanford.edu/browse/SWAPPS-214)
Meta PVs help users browse and identify snapshots in the snapshot table.
Test suite passes
> ENH / GUI: add meta PV columns to snapshot table

- superscore/tests/test_window.py
- superscore/widgets/window.py
- Refactor Window:
- use a StackedLayout to hold the different views - this means state persists even when changing view
- remove Splitter as user control of navbar width is not necessary
- refactoring to standardize how content views are initialized
- individual snapshot views tracked in a dict to prevent duplicate views from spawning and allow for cleanup steps
- Navigation Panel functionality:
- Style for buttons including hover
- Expand and collapse panel including appropriate styling and content changes 
- Tooltips for nav buttons so function can be understood even when collapsed
- Button style for currently selected view only triggers when that view is actually rendered - you can see this with the not-yet-implemented Configure Tags view.
- Tests:
- Test to check that switching views …
> GUI: Expand/collapse nav panel, nav panel button style, refactor Window

- superscore/tests/test_window.py
- superscore/widgets/page/page.py
- superscore/widgets/page/snapshot_details.py
- superscore/widgets/pv_table.py
- superscore/widgets/snapshot_table.py
- superscore/widgets/window.py
Add the details for a snapshot to the Snapshot Details page. This tells the user the title and creation time of the selected snapshot.
In addition, I made a paging system for the main application. This consists of a Page widget that the Snapshot Details page subclasses. This resulted in a lot of moving code to a new file, which is why the PR is so large.
[SWAPPS-224](https://jira.slac.stanford.edu/browse/SWAPPS-224)
Interactively
>  ENH: Snapshot Information on Snapshot Details Page

- superscore/tests/conftest.py
- superscore/tests/conftest_data.py
- superscore/tests/test_page.py
- superscore/widgets/page/page.py
- superscore/widgets/page/snapshot_comparison.py
- superscore/widgets/snapshot_comparison_table.py
- superscore/widgets/window.py
Allow users to select a snapshot to compare the main snapshot to. The comparison table shows the differences between the 2 snapshots, and highlights the differences in values.
Users should be able to compare 2 existing snapshots as requested in Jira ticket [SWAPPS-229](https://jira.slac.stanford.edu/browse/SWAPPS-229)
Interactively & added tests to test suite
This PR
> ENH: Snapshot Comparison

- superscore/ui/name_desc_tags_widget.ui
- superscore/widgets/core.py
- superscore/widgets/window.py
* Remove logic that sets name `QLineEdit` fixed width whenever text changes
* Remove unused `extra_text_label` and unnecessary spacer
* Remove overriding `showEvent` and `resizeEvent` methods that lock description text edit height to the existing text
* Resize dialog window to expand horizontal space, which is more natural for text
The original looks ugly and acts wonky
👁️ Look at it 👁️ 
☝️ 
Original
Updated
> GUI: simplify and improve editing widgets' sizing in NameDescTagsWidget

- superscore/bin/main.py
- superscore/permission_manager.py
- superscore/tests/test_configure_window.py
- superscore/widgets/configure_window.py
- superscore/widgets/window.py
Builds out the configure page for the admins to modify groups and tags in Squirrel. 
Threw in the beginnings of the light mode style-sheet, it needs some detail work though. 
Closes [SWAPPS-203](https://jira.slac.stanford.edu/browse/SWAPPS-203)
the page is not implemented, and will be crucial for the admins to set up the application.   
Unit tests added, also tested the GUI by inspection 
it has doctrings, but will need a some documentation/walk through made for users.
> ENH: Configure Page

- superscore/widgets/window.py
https://jira.slac.stanford.edu/browse/SWAPPS-263
When the client attempts to retrieve data for alarm limits, it returns either EpicsData or CommunicationError.
Added checks to make sure it is the expected type before attempting to access the data, which should prevent it from crashing the app if unable to access the PV and a CommunicationError was returned.
> ENH: Add check after retrieving epics data

- superscore/widgets/pv_details_components.py
- superscore/widgets/tag.py
- superscore/widgets/window.py
Adds the implemented TagsWidget to the PV details popups. Also adds some helper functions to TagsWidget to make it easier to control and retrieve data from the child TagChips. To type hint it, I had to move TagsWidget to the bottom of the file.
I observed some issues related to the tag chips:
- Non-editable chip style broke - apparently this is pretty finicky
- TagEditor doesn't correctly set selected tags - this results in clearing the tags when first modifying them
By the way, only the read-only pv details popup is currently in use - where would the editable one go?
> GUI: Add tags to PVDetails

- superscore/widgets/page/snapshot_comparison.py
- superscore/widgets/page/snapshot_details.py
- superscore/widgets/window.py
* Switch all `QTableView` columns with `ResizeToContents` resize mode to `Fixed`
* Call `QTableView.resizeColumnsToContents` once on initialization to set reasonable column widths
* Dynamically size comparison dialog on initialization to show whole table width
* Use main window's snapshot table as model for comparison dialog's proxy model
The `ResizeToContents` resize mode is relatively expensive, because it requires finding the widest cell in a column for each resize. Computing those widths once and then keeping them fixed saves the later, largely redundant computation.  We can call `QTableView.resizeColumnsToContents` additional times as needed, such as if new data is fetched and we want to make sure the columns resize properly. We can also change `Fixed` to `Interactive` so that users …
> MNT: improve table view performance by only resizing columns to contents as needed

- superscore/widgets/page/snapshot_comparison.py
- superscore/widgets/page/snapshot_details.py
- superscore/widgets/pv_browser_table.py
- superscore/widgets/pv_table.py
- superscore/widgets/snapshot_table.py
- superscore/widgets/squirrel_table_view.py
- superscore/widgets/window.py
* implement `SquirrelTableView`, which includes some basic table styling, and use for snapshot list, PV details, and comparison tables
* implement `SquirrelTableView.copy_address`, which copies tooltip data to clipboard
* intercept table middle-clicks to call `.copy_address`
* add `ToolTipRole` data to `SnapshotTableModel` and `PVTableModel`
Operators are used to being able to middle-click widgets to display the underlying epics address and copy it to the clipboard.  This functionality this also built in to `PyDMPrimitiveWidget`.  Providing this feature for PV-related tables thus improves user experience and utility.
Closes [SWAPPS-262](https://jira.slac.stanford.edu/browse/SWAPPS-262)
Partially resolves [SWAPPS-261](https://jira.slac.stanford.edu/browse/SWAPPS-261)
> GUI: copy underlying epics address when middle-clicking table cell

- superscore/tests/test_page.py
* remove all instances of `qtbot.wait_until` from `tests/test_pages.py`
These intermittent failures don't point to any known problem, and are super annoying. 
Closes [SWAPPS-238](https://jira.slac.stanford.edu/browse/SWAPPS-238)
> TST: remove tests with intermittent timeout errors

- superscore/tests/test_widgets.py
- superscore/widgets/flow_layout.py
- superscore/widgets/page/pv_browser.py
- superscore/widgets/pv_browser_table.py
- superscore/widgets/tag.py
* implement custom `TagChip.paint()` and `TagsWidget.paint()`
* implement `TagDelegate`
* set delegate on table on PV browser page
`TagChip`s are visually clear representations of tag data, especially compared to `set` strings or plaintext lists of tag names.
There is a known bug in how `TagChip`s are hidden within a `TagsWidget`: our custom `FlowLayout` assigns positions to all child widgets, and attempting to skip hidden widgets breaks how all children are painted. Because of this, hiding children is achieved by skipping them in `TagsWidget.paint()`.  However, the layout still returns a `sizeHint` that includes the hidden widgets, disrupting how table cells are sized.  See the second image for an example.
Closes [SWAPPS-282](https://jira.slac.stanford.edu/browse/SWAPPS-282)
Relates to …
> GUI: display TagChips in table views

- superscore/tests/test_configure_window.py
- superscore/widgets/configure_window.py
- superscore/widgets/tag.py
* apply margins inside `.paintEvent()` when `TagChip`'s size is larger than its sizehint
* set `TagChip` as cell widget for first column of configure tags table
* adjust configure tags table data to be compatible with `TagChip`
* remove unused commented-out code 
Improves visual cohesion by displaying information consistently across the app.
Closes [SWAPPS-286](https://jira.slac.stanford.edu/browse/SWAPPS-286)
Before changes:
With changes:
> GUI: use TagChip in configure tags table

- conda-recipe/meta.yaml
- pyproject.toml
- requirements.txt
- superscore/tests/test_widgets.py
- superscore/widgets/page/diff.py
- superscore/widgets/page/pv_browser.py
- superscore/widgets/page/search.py
- superscore/widgets/page/snapshot_comparison.py
- superscore/widgets/page/snapshot_details.py
- superscore/widgets/tag.py
- superscore/widgets/window.py
The PyQt5 package appears to no longer be available through conda channels. Plus, we're planning to transition towards pyside6 (eventually) anyway, so it doesn't hurt to get ahead.
Requires some code modifigurations for compatibility: mostly adding an enum reference inbetween a widget class and an enum member.
Pytest now produces a few warnings, but these are mostly in apischema, test_qt_helpers.py, and databridges which are likely to face removal anyway.
> BLD: swap PyQt5 req for pyside6

- superscore/widgets/page/snapshot_details.py
- superscore/widgets/window.py
* use `QtCore.Qt.CaseSensitivity` enum as parameter in `QSortFilterProxyModel.setFilterCaseSensitivity`
Fixes compatibility with pyside6
> BUG: use pyside6 enum when setting filter case sensitivity

- superscore/widgets/window.py
Adds a resizeRowsToContents() call to correctly set the expected size for rows in the PV Browser table. 
There is a line in PVBrowserPage which resizes the columns:
https://github.com/slaclab/superscore/blob/b6717b4f4dcb17844b30614e561aedc3da4792dc/superscore/widgets/page/pv_browser.py#L57
Putting the row resize there didn't work - seems like it has to be called after the page is set as the current widget.
Fixes bug where too much vertical space was allocated to each row in the PV Browser Table.
[SWAPPS-275](https://jira.slac.stanford.edu/browse/SWAPPS-275)
Added a comment in the code to explain why it's there.
https://github.com/user-attachments/assets/036a9295-71d5-4add-8738-8b15b1871f72
> BUG: Fix PVBrowser TagWidget vertical size allocation

- superscore/tests/conftest_data.py
- superscore/tests/test_snapshot_table.py
- superscore/widgets/filter_bar.py
- superscore/widgets/snapshot_table.py
- superscore/widgets/window.py
Updates the snapshot GUI to allow for filtering the snapshot table based on meta pv values.
Creates a widget for applying filters based on meta pv column names. Integrates with existing filtering.
Currently assumes that meta pvs are numbers that are compared with numerical operators. If strings are valid too, can easily extend that functionality and include additional operators.
Closes [SWAPPS-116](https://jira.slac.stanford.edu/browse/SWAPPS-116)
Tested interactively, added a new test case to the test suite.
> ENH: Add ability to filter snapshots based on meta pvs

- superscore/widgets/squirrel_table_view.py
* access clipboard selection mode through a PySide6 enum
Allows user to copy strings via mouse middle-click
> BUG: support middle-click copy with PySide6

- superscore/widgets/window.py
* map index from snapshot proxy model to source model before opening
When filters are applied to the snapshot table, attempting to open a snapshot via double-click opens the incorrect snapshot. Mapping the proxy index to the source index before opening fixes this bug.
> BUG: open correct snapshot when snapshot table has filters applied

- docs/source/import_format.rst
- docs/source/index.rst
- superscore/backends/mongo.py
- superscore/tests/test_utils.py
- superscore/utils.py
- superscore/widgets/page/pv_browser.py
- superscore/widgets/pv_browser_table.py
- superscore/widgets/tag.py
* add `MongoBackend.add_multiple_pvs` for atomically pushing multiple PVs to the backend at once
* add logic to parse a csv file into `PV`s
* add `Import PVs` button to PV browser page
* implement table model and view for previewing parsed PVs
Importing PVs enables changes to be programmatic rather than manual, which improves speed, data integrity, and accountability.  If any PV cannot be added, the backend will reject the entire update, so the file used for the update will be a matching record of a successful update.
The backend requires imports to be relatively quick, so importing more than ~1000 PVs at once is currently infeasible. Importing the entire PV configuration (~36,000 PVs) took approximately 15 minutes while importing ~1000 PVs took approximately a minute.  As the backend is …
> ENH: implement importing PVs from a file
